name: dev-env-oncallsla
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-oncallsla:/var/lib/mysql

volumes:
  mysql-data-oncallsla: