spring:
  application:
    name: sla
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oncall
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase.change-log: classpath:/db/changelog/db-changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

oncall:
  sla:
    cron: '0/10 * * ? * *'
    prometheus-host: 'http://metrics.oncall.local'